"""Plotting library for CSM results comparisons."""

import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter

from csm import get_model


def plot_mass_cost_comparison(
    base_kwargs: dict[str, dict],
    parameterization: dict[str, list],
    component: str,
    parameter_label: str,
    reference_turbines: dict[str, dict] | None = None,
    background_data: pd.DataFrame | None = None,
    mass_units: str = "tonnes",
    cost_basis: str = "millions",
    save_name: str | Path | None = None,
    fig_kwargs: dict | None = None,
    legend_kwargs: dict | None = None,
    reference_scatter_kwargs: dict | None = None,
    background_scatter_kwargs: dict | None = None,
    plot_kwargs: dict | None = None,
    axis_label_kwargs: dict | None = None,
    model_plot_settings: dict[str, str] | None = None,
    turbine_scatter_settings: dict[str, str] | None = None,
    mass_xlim: tuple[float, float] | None = None,
    mass_ylim: tuple[float, float] | None = None,
    cost_xlim: tuple[float, float] | None = None,
    cost_ylim: tuple[float, float] | None = None,
    *,
    return_fig_ax: bool = False,
) -> None | tuple[plt.Figure, tuple[plt.Axes, plt.Axes]]:
    """Plots a 2-column figure of a focal parameter vs :py:attr:`component` mass and
    :py:attr:`component` mass vs :py:attr:`component` cost for a set of cost and scaling
    model(s). Additional reference turbine scatter points and empirical/background scatter
    points can be added to be shown against the models' scaling curves.

    Args:
        base_kwargs (dict[str, dict]): Base configuration for each of the models in the form of
            model names as keys and configuration dictionary as values. See
            :py:function:`csm.get_model` for more details on model naming possibilities. The keys
            will be used for the figure legend.
        parameterization (dict[str, list]): The parameterization input to
            :py:meth:`CSMBase.parameterize_subset`. Note that only the first parameter will be used
            if multiple are provided.

            Dictionary of independent variables with an iterable value consisting of an explicit set
            of values or range of values generated by ``np.linspace``. For both cases, the first
            value must be one of "inputs" or "range". Subsequent values should specified according
            to the case:

            - "inputs": all subsequent values will be used as inputs, e.g.,
                {"tower_length": ("inputs", 90, 100)} will run 2 iterations, one with a 90m tower
                length and one with a 100 meter tower length.
            - "range": subsequent values must be start, stop, num where stop is inclusive,
                e.g., {"efficiency_max": ("range", 0.8, 1.0, 5)} will run 5 iterations of the
                model varying ``efficiency_max`` with values 0.8, 0.85, 0.9, 0.95, and 1.0.
        component (str): The name of the turbine component to calculate its respective mass and
            cost. For available options, see :py:meth:`CSMBase.output_names`
        parameter_label (str): Axis label for the parameter values, e.g., "Blade Mass (kg)".
        reference_turbines (dict[str, dict] | None, optional): Dictionary of turbine names as keys
            and model compliant configuration dictionaries that will be used to display each
            turbine's output on the models' scaling curves. The dictionary keys will be used as
            the legend labels. Defaults to None.
        background_data (pd.DataFrame | None, optional): ``pandas.DataFrame`` of empirical data
            points with rows representing turbines and column names matching the naming scheme from
            the model, i.e., use "rotor_diameter", not "Rotor Diameter" or "rated_power_kw", not
            "MW". Additionally, ensure the units match the models' units, i.e., kW, kg, USD, etc.
            Defaults to None.
        mass_units (str, optional): One of "kg" or "tonnes" (metric tonnes) to automatically scale
            mass units. Defaults to "tonnes".
        cost_basis (str, optional): One of "dollars", "thousands", or "millions" to automatically
            scale the cost-basis. Defaults to "millions".
        save_name (str | Path | None, optional): If provided, the figure will be saved to the file
            location. Defaults to None.
        fig_kwargs (dict | None, optional): Keyword arguments passed to ``plt.figure()``.
            Defaults to None.
        legend_kwargs (dict | None, optional): Keyword arguments passed to ``Figure.legend()``.
            Defaults to None.
        reference_scatter_kwargs (dict | None, optional): Keyword arguments passed to
            ``Axes.scatter()`` when plotting the reference turbine data. Defaults to None.
        background_scatter_kwargs (dict | None, optional): Keyword arguments passed to
            ``Axes.scatter()`` when plotting the empirical/background data points. Defaults to None.
        plot_kwargs (dict | None, optional): Keyword arguments passed to ``Axes.plot()`` when
            plotting the model scaling curves. Defaults to None.
        axis_label_kwargs (dict | None, optional): Keyword arguments passed to each
            ``Axes.set_xlabel()`` and ``Axes.set_ylabel()``. Defaults to None.
        model_plot_settings (dict[str, str] | None, optional): Keyword arguments passed to
            ``Axes.plot()`` when plotting the individual model scaling curves. Use this to control
            model-specific plotting elements with keys matching :py:attr:`base_kwargs`. Defaults to
            None.
        turbine_scatter_settings (dict[str, str] | None, optional): Keyword arguments passed to
            ``Axes.scatter()`` when plotting the reference turbines. Use this to control
            turbine-specific plotting elements with keys matching :py:attr:`reference_turbines`.
            Defaults to None.
        mass_xlim (tuple[float, float] | None, optional): X-axis limits for the parameter vs mass
            figure. Defaults to None.
        mass_ylim (tuple[float, float] | None, optional): Y-axis limits for the parameter vs mass
            figure. Defaults to None.
        cost_xlim (tuple[float, float] | None, optional): X-axis limits for the mass vs cost
            figure. Defaults to None.
        cost_ylim (tuple[float, float] | None, optional): Y-axis limits for the mass vs cost
            figure. Defaults to None.
        return_fig_ax (bool, optional): If True, return the figure and axes objects as
            ``(fig, (ax1, ax2))``. Defaults to False.

    Raises:
        ValueError: Raised if an invalid input is provided to :py:attr:`mass_units`.
        ValueError: Raised if an invalid input is provided to :py:attr:`cost_basis`.

    Returns:
        None | tuple[plt.Figure, tuple[plt.Axes, plt.Axes]]: ``Figure`` and ``Axes`` objects
            returned if :py:attr:`return_fig_ax` is True, otherwise None.
    """
    # Handle None defaults for expected non-None types
    fig_settings = {"dpi": 200, "figsize": (9, 4)}
    if fig_kwargs is not None:
        fig_settings.update(fig_kwargs)

    legend_settings = {}
    if legend_kwargs is not None:
        legend_settings.update(legend_kwargs)

    reference_scatter_settings = {}
    if reference_scatter_kwargs is not None:
        reference_scatter_settings.update(reference_scatter_kwargs)

    background_scatter_settings = {}
    if background_scatter_kwargs is not None:
        background_scatter_settings.update(background_scatter_kwargs)

    plot_settings = {}
    if plot_kwargs is not None:
        plot_settings.update(plot_kwargs)

    axis_label_settings = {}
    if axis_label_kwargs is not None:
        axis_label_settings.update(axis_label_kwargs)

    if turbine_scatter_settings is None:
        turbine_scatter_settings = {}

    if model_plot_settings is None:
        model_plot_settings = {}

    # Create models and results
    metrics = [f"{component}_mass", f"{component}_cost"]
    models = {name: get_model(name) for name in base_kwargs}
    parameter = next(iter(parameterization))
    if len(parameterization) > 1:
        msg = f"'parameterization' has multiple entries, only '{parameter}' will be used."
        warnings.warn(msg, UserWarning, stacklevel=1)

    results = {
        name: model.parameterize_subset(base_kwargs[name], parameterization, metrics)
        for name, model in models.items()
    }

    # Handle mass and cost units
    match mass_units.lower():
        case "kg":
            label_units = "kg"
            mass_scale = 1
        case "tonnes":
            mass_scale = 1 / 1e3
            label_units = "Metric Tonnes"
        case _:
            raise ValueError("'mass_units' should be one of 'kg' or 'tonnes'.")

    match cost_basis.lower():
        case "dollars":
            label_cost = "USD"
            cost_scale = 1
        case "thousands":
            cost_scale = 1 / 1e3
            label_cost = "Thousands USD"
        case "millions":
            cost_scale = 1 / 1e6
            label_cost = "Millions USD"
        case _:
            raise ValueError("'cost_basis' should be one of 'dollars', 'thousands', 'millions'.")

    mass_label = f"{component.title()} Mass ({label_units})"
    cost_label = f"{component.title()} Cost ({label_cost})"

    # Plotting setup
    fig = plt.figure(**fig_settings)
    ax1, ax2 = fig.subplots(1, 2)

    ax1.set_xlabel(parameter_label, **axis_label_settings)
    ax1.set_ylabel(mass_label, **axis_label_settings)
    ax2.set_xlabel(mass_label, **axis_label_settings)
    ax2.set_ylabel(cost_label, **axis_label_settings)

    ax1.set_xlim(mass_xlim)
    ax1.set_ylim(mass_ylim)
    ax2.set_xlim(cost_xlim)
    ax2.set_ylim(cost_ylim)

    for ax in (ax1, ax2):
        ax.xaxis.set_major_formatter(StrMethodFormatter("{x:,.0f}"))
        ax.yaxis.set_major_formatter(StrMethodFormatter("{x:,.0f}"))
        ax.grid()
        ax.set_axisbelow(True)

    # Model line plots
    for name, _results in results.items():
        parameter_values = _results.columns
        mass = _results.loc[f"{component}_mass"] * mass_scale
        cost = _results.loc[f"{component}_cost"] * cost_scale

        formatting = plot_settings | model_plot_settings.get(name, {})
        ax1.plot(parameter_values, mass, label=name, **formatting)
        ax2.plot(mass, cost, **plot_settings, **formatting)

    # Background scatter points
    if background_data is not None:
        scatter_data = background_data.loc[:, [parameter, *metrics]]
        parameter_values = scatter_data[parameter].to_numpy()
        mass = scatter_data[metrics[0]].to_numpy() * mass_scale
        cost = scatter_data[metrics[1]].to_numpy() * cost_scale
        ax1.scatter(
            parameter_values, mass, **({"label": "Empirical Data"} | background_scatter_settings)
        )
        ax2.scatter(mass, cost, **background_scatter_settings)

    # Reference turbine scatter plots
    # TODO: reference turbine scatter plots
    if reference_turbines is None:
        reference_turbines = {}
    for turbine, config in reference_turbines.items():
        if (parameter_value := config.get(parameter)) is None:
            continue
        turbine_models = {
            name: model.from_dict(config, partial=True) for name, model in models.items()
        }
        [model.calculate(*metrics) for model in turbine_models.values()]

        parameter_values = [parameter_value] * len(turbine_models)
        mass = [getattr(model, f"{component}_mass") for model in turbine_models.values()]
        cost = [getattr(model, f"{component}_cost") for model in turbine_models.values()]
        mass = np.array(mass) * mass_scale
        cost = np.array(cost) * cost_scale

        formatting = reference_scatter_settings | turbine_scatter_settings.get(turbine, {})
        ax1.scatter(parameter_values, mass, label=turbine, **formatting)
        ax2.scatter(mass, cost, **formatting)

    # TODO: background data scatter for industry data points

    # Post-plot figure handling
    fig.legend(**legend_settings)

    fig.tight_layout()
    if save_name is not None:
        fig.savefig(save_name, bbox_inches="tight")

    if return_fig_ax:
        return fig, (ax1, ax2)
