"""Auto-generated by build_custom_model.py — coefficients fit from empirical data.

Fit from us_lbw_csm_2026_data.csv and WM_wind_capex_benchmark_data_geared.csv. Mass formula shapes
default to Land2020NLR, except: Tower=Land2015NLR, Bedplate=Land2015NLR.

Do not hand-edit this file; rerun the fitting script instead so the model and its fit report stay in
sync.
"""

from attrs import define, fields

from csm.models.utils import create_field
from csm.models.nlr2020 import Land2020NLR


SHAPE_OVERRIDES = {"Tower": "2015", "Bedplate": "2015"}


base = fields(Land2020NLR)


@define
class Land2026NLR(Land2020NLR):
    """Coefficients fit from empirical data; formula shapes are inherited from `Land2020NLR`
    unless noted. See the accompanying fit report for what was fit vs. inherited, and from how
    many data points.
    """

    converter_cost_coeff = create_field(float, "unitless", "input", default=34.948389651183895)
    converter_cost_intercept = create_field(float, "unitless", "input", default=60252.69153967121)
    tower_mass_exp = create_field(float, "unitless", "input", default=1.5021874164036764)
    bedplate_mass_exp = create_field(float, "unitless", "input", default=2.0087767653732453)

    blade_mass_coeff = base.blade_mass_coeff.reuse(default=6.2335566828285724)
    blade_mass_exp = base.blade_mass_exp.reuse(default=1.8822588627457848)
    hub_mass_coeff = base.hub_mass_coeff.reuse(default=0.9844560807877597)
    hub_mass_intercept = base.hub_mass_intercept.reuse(default=-2815.3779336308144)
    gearbox_torque_density = base.gearbox_torque_density.reuse(default=156.2468827613726)
    gearbox_torque_exp = base.gearbox_torque_exp.reuse(default=0.6428251218922734)
    generator_mass_coeff = base.generator_mass_coeff.reuse(default=1.6504998114215377)
    generator_mass_intercept = base.generator_mass_intercept.reuse(default=4457.4221007968745)
    tower_mass_coeff = base.tower_mass_coeff.reuse(default=272.0188367382834)
    lss_mass_coeff1 = base.lss_mass_coeff1.reuse(default=1.1802341739414148)
    lss_mass_coeff2 = base.lss_mass_coeff2.reuse(default=-1.8499663205161596)
    lss_mass_intercept = base.lss_mass_intercept.reuse(default=-315.5873904621458)
    transformer_mass_coeff = base.transformer_mass_coeff.reuse(default=2.1052631578947367)
    transformer_mass_intercept = base.transformer_mass_intercept.reuse(default=2421.0526315789475)
    pitch_system_mass_coeff = base.pitch_system_mass_coeff.reuse(default=3.7281609429696583)
    mass_sys_offset = base.mass_sys_offset.reuse(default=666.7444973312695)
    brake_mass_cost_coeff = base.brake_mass_cost_coeff.reuse(default=5.244211405822075)
    hvac_mass_cost_coeff = base.hvac_mass_cost_coeff.reuse(default=95.62973740028488)
    nacelle_cover_mass_cost_coeff = base.nacelle_cover_mass_cost_coeff.reuse(
        default=4.395883090174387
    )
    transformer_mass_cost_coeff = base.transformer_mass_cost_coeff.reuse(default=14.498702121978676)
    controls_cost_coeff = base.controls_cost_coeff.reuse(default=16.311039887226013)
    electrical_connection_cost_coeff = base.electrical_connection_cost_coeff.reuse(
        default=32.275036372596155
    )
    lss_mass_cost_coeff = base.lss_mass_cost_coeff.reuse(default=7.514314915542846)
    bearing_mass_cost_coeff = base.bearing_mass_cost_coeff.reuse(default=15.213713955616889)
    blade_mass_cost_coeff = base.blade_mass_cost_coeff.reuse(default=14.998321779915484)
    gearbox_mass_cost_coeff = base.gearbox_mass_cost_coeff.reuse(default=11.48883875665904)
    generator_mass_cost_coeff = base.generator_mass_cost_coeff.reuse(default=14.034197143438742)
    hub_mass_cost_coeff = base.hub_mass_cost_coeff.reuse(default=4.033635706860739)
    pitch_system_mass_cost_coeff = base.pitch_system_mass_cost_coeff.reuse(
        default=6.087045175579616
    )
    spinner_mass_cost_coeff = base.spinner_mass_cost_coeff.reuse(default=3.0572941832096716)
    bedplate_mass_cost_coeff = base.bedplate_mass_cost_coeff.reuse(default=3.152684795090467)
    yaw_system_mass_cost_coeff = base.yaw_system_mass_cost_coeff.reuse(default=21.381629102767096)
    platform_mainframe_mass_cost_coeff = base.platform_mainframe_mass_cost_coeff.reuse(
        default=44.05130815148402
    )
    tower_mass_cost_coeff = base.tower_mass_cost_coeff.reuse(default=3.1341109214450307)

    def calculate_converter_cost(self):
        """Structural override: cost is fit directly against turbine rating, with an
        intercept (unlike every other current cost formula), instead of the base
        model's always-zero converter mass, regardless of the base model.
        """
        exists = self._prepare_calculation("converter_cost")
        if exists:
            return
        self.converter_cost = (
            self.converter_cost_coeff * self.rated_power_kw + self.converter_cost_intercept
        )

    def calculate_tower_mass(self):
        """Structural override: this component specifically uses Land2015NLR/
        CSMBase's simpler hub-height-only shape, instead of this model's own base
        class's native shape.
        """
        exists = self._prepare_calculation("tower_mass")
        if exists:
            return
        self.tower_mass = self.tower_mass_coeff * self.tower_length**self.tower_mass_exp

    def calculate_bedplate_mass(self):
        """Structural override: this component specifically uses Land2015NLR/
        CSMBase's simpler rotor-diameter-only shape, instead of this model's own
        base class's native shape.
        """
        exists = self._prepare_calculation("bedplate_mass")
        if exists:
            return
        self.bedplate_mass = self.rotor_diameter**self.bedplate_mass_exp

    def __attrs_post_init__(self):
        """Applies structural formula overrides not natively present on the base model."""
        self.parameter_map["converter_cost"] = (
            "converter_cost_coeff",
            "rated_power_kw",
            "converter_cost_intercept",
        )
        self.parameter_map["tower_mass"] = ("tower_mass_coeff", "tower_length", "tower_mass_exp")
        self.parameter_map["bedplate_mass"] = (
            "rotor_diameter",
            "bedplate_mass_exp",
        )
        super().__attrs_post_init__()
