"""Auto-generated by csm/build_custom_model.py — coefficients fit from empirical data.

Fit from us_lbw_csm_2026_data.csv and WM_wind_capex_benchmark_data_geared.csv. Mass formula shapes default to Land2020NLR, except: Tower=Land2015NLR, Bedplate=Land2015NLR.

Do not hand-edit this file; rerun the fitting script instead so the model and its fit report
stay in sync.
"""

from attrs import define, fields
from csm.models.utils import create_field
from csm.models.nlr2020 import Land2020NLR


SHAPE_OVERRIDES = {'Tower': '2015', 'Bedplate': '2015'}


base = fields(Land2020NLR)


@define
class Land2026NLR(Land2020NLR):
    """Coefficients fit from empirical data; formula shapes are inherited from `Land2020NLR` unless noted. See the accompanying fit report for what was fit vs. inherited, and from how many data points."""

    converter_cost_coeff = create_field(float, "unitless", "input", default=33.57534106257999)
    converter_cost_intercept = create_field(float, "unitless", "input", default=68507.14681904303)
    tower_mass_exp = create_field(float, "unitless", "input", default=1.5181846928168339)
    bedplate_mass_exp = create_field(float, "unitless", "input", default=2.2)

    blade_mass_coeff = base.blade_mass_coeff.reuse(default=5.745819798678461)
    blade_mass_exp = base.blade_mass_exp.reuse(default=1.9069980016219674)
    hub_mass_coeff = base.hub_mass_coeff.reuse(default=2.2558305346032386)
    hub_mass_intercept = base.hub_mass_intercept.reuse(default=669.1790411150027)
    gearbox_torque_density = base.gearbox_torque_density.reuse(default=238.9965435531631)
    gearbox_torque_exp = base.gearbox_torque_exp.reuse(default=0.5918392306570984)
    generator_mass_coeff = base.generator_mass_coeff.reuse(default=1.7702550634939713)
    generator_mass_intercept = base.generator_mass_intercept.reuse(default=3861.798575570715)
    tower_mass_coeff = base.tower_mass_coeff.reuse(default=255.93668236233714)
    transformer_mass_coeff = base.transformer_mass_coeff.reuse(default=2.1052631578947367)
    transformer_mass_intercept = base.transformer_mass_intercept.reuse(default=2421.0526315789475)
    brake_mass_cost_coeff = base.brake_mass_cost_coeff.reuse(default=4.864547074957965)
    hvac_mass_cost_coeff = base.hvac_mass_cost_coeff.reuse(default=88.70644666099818)
    nacelle_cover_mass_cost_coeff = base.nacelle_cover_mass_cost_coeff.reuse(default=4.07763504812653)
    transformer_mass_cost_coeff = base.transformer_mass_cost_coeff.reuse(default=13.44904191311908)
    controls_cost_coeff = base.controls_cost_coeff.reuse(default=15.130172152258966)
    electrical_connection_cost_coeff = base.electrical_connection_cost_coeff.reuse(default=29.93842574808689)
    bearing_mass_cost_coeff = base.bearing_mass_cost_coeff.reuse(default=15.213713955616889)
    lss_mass_cost_coeff = base.lss_mass_cost_coeff.reuse(default=13.975580517638475)
    hss_mass_cost_coeff = base.hss_mass_cost_coeff.reuse(default=0.0)
    blade_mass_cost_coeff = base.blade_mass_cost_coeff.reuse(default=16.280401029267715)
    gearbox_mass_cost_coeff = base.gearbox_mass_cost_coeff.reuse(default=10.773144429474796)
    generator_mass_cost_coeff = base.generator_mass_cost_coeff.reuse(default=17.599148399236004)
    hub_mass_cost_coeff = base.hub_mass_cost_coeff.reuse(default=2.0446113666083128)
    pitch_system_mass_cost_coeff = base.pitch_system_mass_cost_coeff.reuse(default=11.586131077447105)
    spinner_mass_cost_coeff = base.spinner_mass_cost_coeff.reuse(default=5.819278504962121)
    bedplate_mass_cost_coeff = base.bedplate_mass_cost_coeff.reuse(default=2.3469274678647727)
    yaw_system_mass_cost_coeff = base.yaw_system_mass_cost_coeff.reuse(default=6.717068270095728)
    platform_mainframe_mass_cost_coeff = base.platform_mainframe_mass_cost_coeff.reuse(default=13.838779207064695)
    tower_mass_cost_coeff = base.tower_mass_cost_coeff.reuse(default=3.334581968301938)

    def calculate_converter_cost(self):
        """Structural override: cost is fit directly against turbine rating, with an
        intercept (unlike every other current cost formula), instead of the base
        model's always-zero converter mass, regardless of the base model.
        """
        exists = self._prepare_calculation("converter_cost")
        if exists:
            return
        self.converter_cost = (
            self.converter_cost_coeff * self.rated_power_kw + self.converter_cost_intercept
        )

    def calculate_tower_mass(self):
        """Structural override: this component specifically uses Land2015NLR/
        CSMBase's simpler hub-height-only shape, instead of this model's own base
        class's native shape.
        """
        exists = self._prepare_calculation("tower_mass")
        if exists:
            return
        self.tower_mass = self.tower_mass_coeff * self.tower_length**self.tower_mass_exp

    def calculate_bedplate_mass(self):
        """Structural override: this component specifically uses Land2015NLR/
        CSMBase's simpler rotor-diameter-only shape, instead of this model's own
        base class's native shape.
        """
        exists = self._prepare_calculation("bedplate_mass")
        if exists:
            return
        self.bedplate_mass = self.rotor_diameter**self.bedplate_mass_exp

    def __attrs_post_init__(self):
        """Applies structural formula overrides not natively present on the base model."""
        self.parameter_map["converter_cost"] = ("converter_cost_coeff", "rated_power_kw", "converter_cost_intercept")
        self.parameter_map["tower_mass"] = ("tower_mass_coeff", "tower_length", "tower_mass_exp")
        self.parameter_map["bedplate_mass"] = ("rotor_diameter", "bedplate_mass_exp")
        super().__attrs_post_init__()

