"""Auto-generated by build_custom_osw_model.py — coefficients fit from empirical and benchmark
offshore wind data.

Fit from osw_csm_2026_data.csv (mass, shared with the other offshore type) and
osw_benchmark_data.csv (cost, fixed-bottom only).

Do not hand-edit this file; rerun the fitting script instead so the model and its fit report stay in
sync.
"""

from attrs import define, fields

from csm.models.base_osw_model import OSWBase


base = fields(OSWBase)


@define
class OffshoreFB2024NLR(OSWBase):
    """Coefficients fit from empirical and benchmark offshore wind data. See the accompanying fit
    report for what was fit and from how many data points.
    """

    blade_mass_coeff = base.blade_mass_coeff.reuse(default=8.405983036331634)
    blade_mass_exp = base.blade_mass_exp.reuse(default=1.867299995402094)
    rotor_mass_coeff = base.rotor_mass_coeff.reuse(default=73.24215857108679)
    rotor_mass_exp = base.rotor_mass_exp.reuse(default=1.510196316094674)
    tower_mass_coeff = base.tower_mass_coeff.reuse(default=3.2865604803641135)
    tower_mass_exp = base.tower_mass_exp.reuse(default=2.5113977248495747)
    nacelle_mass_coeff = base.nacelle_mass_coeff.reuse(default=45.33896103179192)
    nacelle_mass_intercept = base.nacelle_mass_intercept.reuse(default=-8082.174776932239)
    rotor_mass_cost_coeff = base.rotor_mass_cost_coeff.reuse(default=24.13266281376339)
    nacelle_mass_cost_coeff = base.nacelle_mass_cost_coeff.reuse(default=22.24764903228274)
    tower_mass_cost_coeff = base.tower_mass_cost_coeff.reuse(default=2.3091366982251182)
